---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- type: file
  name: preview
  label: Preview
pages:
- _posts/test-title-four.md
- _posts/test-title-three.md
- _posts/test-title-two.md
- _posts/test-title-one.md
